@startuml sequenceDiagramSUInt

!pragma teoz true
box "RealWorld" #LightPink
    actor User
    participant Tile as PD
end box

box "Host <<Microsoft HoloLens 2>>" #LightGreen
    participant ExactManager as Exact
    participant Game
    participant NetworkDevice as ND
    participant NetworkThing as NTHL
end box


== Physical Tap ==

User -> PD : Tap
PD -> ND : [MQTT] /exact/<mac>/event/imu/tapped
ND -> Game : OnTapped(device)
Game -> ND : SetColor(color)
ND -> PD : [MQTT] /exact/<mac>/action/led_ring/set_color_all_leds "255/0/255"

'over ND, NTMQ
group ref: Setting color
    ND -> NTHL : SetUniformColor(color)
    NTHL -> NTHL : _color = color
end

||100||
== Virtual Tap on HoloLens ==

rnote across
    Using `<<Select>>` for the event when a user interacts with the virtual object
    Using `<<VirtualTapHappened>>` for the event fired by NetworkThing
endnote

User -> NTHL : <<Select>>
NTHL -> NTHL : VirtualTap()
NTHL -> ND : <<VirtualTapHappened>>

'over PD, NTMQ
' group ref: VirtualTapHappened handling
    ND -> ND : OnTap()
    ND -> Game : OnTapped(device)
    Game -> ND : SetColor(color)
    ND -> PD : [MQTT] /exact/<mac>/action/led_ring/set_color_all_leds "0/0/0"
    hnote over ND, NTHL #GoldenRod
        Same as 'ref: Setting color' in 'Physical Tap'
    endnote
' end

@end

